version: '3.8'

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"  # UI
      - "14268:14268"  # Collector HTTP
      - "6831:6831/udp"  # Agent
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: opstool
      POSTGRES_USER: opstool
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  opstool-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5044:5044"
    environment:
      - PORT=5044
      - REDIS_HOST=redis
      - DB_HOST=postgres
      - DB_USER=opstool
      - DB_PASSWORD=password
      - DB_NAME=opstool
      - JAEGER_ENDPOINT=http://jaeger:14268/api/traces
    depends_on:
      - redis
      - postgres
      - jaeger
    volumes:
      - /var/log:/var/log:ro  # Mount system logs

  opstool-worker:
    build:
      context: .
      dockerfile: deployments/docker/Dockerfile.python
    environment:
      - REDIS_HOST=redis
      - JAEGER_ENDPOINT=http://jaeger:14268/api/traces
    depends_on:
      - redis
      - jaeger
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Docker access

volumes:
  redis_data:
  postgres_data:
