apiVersion: apps/v1
kind: Deployment
metadata:
  name: opstool-worker
  namespace: opstool
spec:
  replicas: 5
  selector:
    matchLabels:
      app: opstool-worker
  template:
    metadata:
      labels:
        app: opstool-worker
    spec:
      containers:
      - name: opstool-worker
        image: opstool/worker:latest
        env:
        - name: REDIS_HOST
          value: "redis"
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: github-secret
              key: token
        volumeMounts:
        - name: docker-sock
          mountPath: /var/run/docker.sock
        - name: workspace
          mountPath: /workspace
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 8081
          name: http-health
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
      - name: workspace
        persistentVolumeClaim:
          claimName: workspace-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: workspace-pvc
  namespace: opstool
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: opstool-worker-hpa
  namespace: opstool
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: opstool-worker
  minReplicas: 3
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80